pic = load('lena_1.mat');
imshow(x,[0 255]);
figure;
imshow(mask,[0 1]);
 corrupted = x .* (ones(size(x))-mask);
 figure;
 imshow(corrupted,[0 255]);
result = inpainting(uint8(corrupted),mask);
 figure;
 imshow(result,[0 255]);
% res = imread('InpaintingCycles/pic.jp2');
% figure;
% imshow(uint8(res),[0 255]);
% restored = (uint8(res) .* uint8(zeros(size(res))+mask)) + uint8(corrupted);
% figure;
% imshow(uint8(restored),[0 255]);